//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sign_Amazon_Integration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sign_Amazon_Integration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:58080.
        /// </summary>
        internal static string dev_api_host {
            get {
                return ResourceManager.GetString("dev_api_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMY1jSDoAaj77pSQX4OTEg==.
        /// </summary>
        internal static string dev_secret_key {
            get {
                return ResourceManager.GetString("dev_secret_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.suryani.cn.
        /// </summary>
        internal static string local_api_host {
            get {
                return ResourceManager.GetString("local_api_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMY1jSDoAaj77pSQX4OTEg==.
        /// </summary>
        internal static string local_secret_key {
            get {
                return ResourceManager.GetString("local_secret_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.quidsi.com.
        /// </summary>
        internal static string prod_api_host {
            get {
                return ResourceManager.GetString("prod_api_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKZQlB7EmLMIqQENAijLYg==.
        /// </summary>
        internal static string prod_secret_key {
            get {
                return ResourceManager.GetString("prod_secret_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.qa.diaperscorp.com.
        /// </summary>
        internal static string qa_api_host {
            get {
                return ResourceManager.GetString("qa_api_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2xDAtrvyK4LYqJnIqcEGTA==.
        /// </summary>
        internal static string qa_secret_key {
            get {
                return ResourceManager.GetString("qa_secret_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.uat.diaperscorp.com.
        /// </summary>
        internal static string uat_api_host {
            get {
                return ResourceManager.GetString("uat_api_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jL365dVG69gfOdREyeb9xA==.
        /// </summary>
        internal static string uat_secret_key {
            get {
                return ResourceManager.GetString("uat_secret_key", resourceCulture);
            }
        }
    }
}
